php:
  image: php:5.6-fpm
  ports:
   - "9000:9000"
  volumes:
   - ./html:/srv/http:ro

nginx:
  image: nginx:latest
  links:
    - php:stackphp
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./html:/usr/share/nginx/html:ro
   - ./config/nginx.conf:/etc/nginx/nginx.conf